global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]
    scrape_interval: 10s

  - job_name: 'k6'
    static_configs:
      - targets: [ 'host.docker.internal:6565' ]
    scrape_interval: 2s